# Generated by Django 2.2 on 2019-04-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=256, null=True)),
                ('password', models.CharField(blank=True, max_length=25, null=True)),
                ('job_name', models.CharField(max_length=128)),
                ('input_data', models.TextField()),
                ('psipred_job', models.BooleanField(default=False)),
                ('disopred_job', models.BooleanField(default=False)),
                ('memsatsvm_job', models.BooleanField(default=False)),
                ('pgenthreader_job', models.BooleanField(default=False)),
                ('mempack_job', models.BooleanField(default=False)),
                ('genthreader_job', models.BooleanField(default=False)),
                ('pdomthreader_job', models.BooleanField(default=False)),
                ('bioserf_job', models.BooleanField(default=False)),
                ('domserf_job', models.BooleanField(default=False)),
                ('ffpred_job', models.BooleanField(default=False)),
                ('metapsicov_job', models.BooleanField(default=False)),
                ('metsite_job', models.BooleanField(default=False)),
                ('hspred_job', models.BooleanField(default=False)),
                ('memembed_job', models.BooleanField(default=False)),
                ('gentdb_job', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServerSuspension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspend', models.BooleanField(default=False)),
                ('message', models.CharField(max_length=512, null=True)),
                ('allowed_ip', models.GenericIPAddressField(default='127.0.0.1')),
            ],
        ),
    ]
