# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_request_disopred_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='memsatsvm_job',
            field=models.BooleanField(default=False),
        ),
    ]
