# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-12 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_request_memsatsvm_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='pgenthreader_job',
            field=models.BooleanField(default=False),
        ),
    ]
