# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-16 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_request_pgenthreader_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='bioserf_job',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='domserf_job',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='ffpred_job',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='gentdb_job',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='genthreader_job',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='hspred_job',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='memembed_job',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='mempack_job',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='metapsicov_job',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='metsite_job',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='pdomthreader_job',
            field=models.BooleanField(default=False),
        ),
    ]
