# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-01-07 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_auto_20180216_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='email',
            field=models.EmailField(blank=True, max_length=256, null=True),
        ),
    ]
