# Generated by Django 3.2.5 on 2021-07-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='dmp_job',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='dmpfold_job',
            field=models.BooleanField(default=False),
        ),
    ]
