# Generated by Django 3.2.5 on 2021-08-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0008_auto_20210601_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.BooleanField(default=False)),
                ('message', models.CharField(max_length=512, null=True)),
            ],
        ),
    ]
