# Generated by Django 3.2.5 on 2023-01-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0009_servermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='s4pred_job',
            field=models.BooleanField(default=False),
        ),
    ]
